---
os: linux
dist: bionic
language: java
addons:
  firefox: latest
  chrome: stable

env:
  - KOTLIN_JS_COMPILER=ir
  - KOTLIN_JS_COMPILER=legacy
  - TARGET_ENGINE=test.chrome
  - TARGET_ENGINE=test.firefox
  - TARGET_ENGINE=test.node

install: >
    ./gradlew assemble -Pkotlin.js.compiler=${KOTLIN_JS_COMPILER}
    && yarn install
script: cd test-ts && npm run ${TARGET_ENGINE}
